<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pavement Maintenance</name>
   <tag></tag>
   <elementGuidId>87c773e0-58b1-4ddf-9dba-997dba4747d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiSelect-root-241.MuiSelect-select-242.MuiSelect-selectMenu-245.MuiInputBase-input-270.MuiInput-input-258</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize Charts'])[1]/following::div[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root-241 MuiSelect-select-242 MuiSelect-selectMenu-245 MuiInputBase-input-270 MuiInput-input-258</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pavement Maintenance</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;makeStyles-root-84&quot;]/div[@class=&quot;MuiBox-root-94 MuiBox-root-95 makeStyles-subPanel-90 makeStyles-subPanel-93&quot;]/div[@class=&quot;MuiBox-root-94 MuiBox-root-98&quot;]/div[@class=&quot;MuiBox-root-94 MuiBox-root-99&quot;]/div[@class=&quot;MuiPaper-root-102 MuiAccordion-root-100 Mui-expanded MuiAccordion-rounded-101 MuiPaper-elevation1-106 MuiPaper-rounded-103&quot;]/div[@class=&quot;MuiCollapse-container-181 MuiCollapse-entered-182&quot;]/div[@class=&quot;MuiCollapse-wrapper-184&quot;]/div[@class=&quot;MuiCollapse-wrapperInner-185&quot;]/div[1]/div[@class=&quot;MuiAccordionDetails-root-186 makeStyles-accordionDetail-85&quot;]/div[1]/div[@class=&quot;sc-hiKfDv fcCmgx&quot;]/div[@class=&quot;MuiBox-root-94 MuiBox-root-240&quot;]/div[@class=&quot;MuiInputBase-root-262 MuiInput-root-251 MuiInput-underline-254&quot;]/div[@class=&quot;MuiSelect-root-241 MuiSelect-select-242 MuiSelect-selectMenu-245 MuiInputBase-input-270 MuiInput-input-258&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div/div/div[5]/div[2]/div/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a layer as data source:'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize Charts'])[1]/following::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a method analyze and display data as charts:'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Count by category'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
