<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Functional Class ID</name>
   <tag></tag>
   <elementGuidId>b6e05769-6157-4ddf-9e5f-9498e56a4127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-field > div.MuiPaper-root-367.MuiMenu-paper-235.MuiPopover-paper-238.MuiPaper-elevation8-378.MuiPaper-rounded-368 > ul.MuiList-root-419.MuiMenu-list-236.MuiList-padding-420 > li.MuiButtonBase-root-131.MuiListItem-root-426.MuiMenuItem-root-423.Mui-selected.MuiMenuItem-gutters-424.MuiListItem-gutters-431.MuiListItem-button-432.Mui-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-field']/div[3]/ul/li[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-131 MuiListItem-root-426 MuiMenuItem-root-423 Mui-selected MuiMenuItem-gutters-424 MuiListItem-gutters-431 MuiListItem-button-432 Mui-selected</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>functional_class_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Functional Class</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-field&quot;)/div[@class=&quot;MuiPaper-root-367 MuiMenu-paper-235 MuiPopover-paper-238 MuiPaper-elevation8-378 MuiPaper-rounded-368&quot;]/ul[@class=&quot;MuiList-root-419 MuiMenu-list-236 MuiList-padding-420&quot;]/li[@class=&quot;MuiButtonBase-root-131 MuiListItem-root-426 MuiMenuItem-root-423 Mui-selected MuiMenuItem-gutters-424 MuiListItem-gutters-431 MuiListItem-button-432 Mui-selected&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-field']/div[3]/ul/li[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Class'])[5]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCI'])[3]/following::li[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Length (ft)'])[5]/preceding::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Width (ft)'])[5]/preceding::li[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]</value>
   </webElementXpaths>
</WebElementEntity>
