<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Chart</name>
   <tag></tag>
   <elementGuidId>1a9dee63-9899-4bb7-8bfd-e88480d5e201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[2]/div[2]/div/div[1]/div/div/div[5]/div[2]/div/div/div/div/div/div[5]/button/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root-384.MuiBox-root-574 > button.MuiButtonBase-root-423.MuiButton-root-575.MuiButton-text-577.MuiButton-textPrimary-578</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-423 MuiButton-root-575 MuiButton-text-577 MuiButton-textPrimary-578</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Chart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;makeStyles-root-374&quot;]/div[@class=&quot;MuiBox-root-384 MuiBox-root-385 makeStyles-subPanel-380 makeStyles-subPanel-383&quot;]/div[@class=&quot;MuiBox-root-384 MuiBox-root-388&quot;]/div[@class=&quot;MuiBox-root-384 MuiBox-root-389&quot;]/div[@class=&quot;MuiPaper-root-392 MuiAccordion-root-390 Mui-expanded MuiAccordion-rounded-391 MuiPaper-elevation1-396 MuiPaper-rounded-393&quot;]/div[@class=&quot;MuiCollapse-container-471 MuiCollapse-entered-472&quot;]/div[@class=&quot;MuiCollapse-wrapper-474&quot;]/div[@class=&quot;MuiCollapse-wrapperInner-475&quot;]/div[1]/div[@class=&quot;MuiAccordionDetails-root-476 makeStyles-accordionDetail-375&quot;]/div[1]/div[@class=&quot;MuiBox-root-384 MuiBox-root-574&quot;]/button[@class=&quot;MuiButtonBase-root-423 MuiButton-root-575 MuiButton-text-577 MuiButton-textPrimary-578&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div/div/div[5]/div[2]/div/div/div/div/div/div[5]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select chart type:'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back to options'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
   </webElementXpaths>
</WebElementEntity>
