<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chechbox_restore_editts</name>
   <tag></tag>
   <elementGuidId>6bd09d19-5260-4400-b2ad-7e9a316400f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='6342']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-386 MuiBox-root-387&quot;]/div[@class=&quot;MuiBox-root-386 MuiBox-root-388&quot;]/div[@class=&quot;MuiBox-root-386 MuiBox-root-505&quot;]/div[@class=&quot;MuiTableContainer-root-506&quot;]/table[@class=&quot;MuiTable-root-507 makeStyles-table-374&quot;]/tbody[@class=&quot;MuiTableBody-root-534&quot;]/tr[@class=&quot;MuiTableRow-root-510&quot;]/td[@class=&quot;MuiTableCell-root-514 MuiTableCell-body-516 MuiTableCell-paddingCheckbox-519 MuiTableCell-sizeSmall-518&quot;]/span[@class=&quot;MuiButtonBase-root-476 MuiIconButton-root-468 PrivateSwitchBase-root-530 MuiCheckbox-root-526 MuiCheckbox-colorPrimary-528 MuiIconButton-colorPrimary-472&quot;]/span[@class=&quot;MuiIconButton-label-475&quot;]/input[@class=&quot;PrivateSwitchBase-input-533&quot;][count(. | //input[@class = 'PrivateSwitchBase-input-533' and @name = '6342' and @type = 'checkbox' and @aria-label = 'Select row']) = count(//input[@class = 'PrivateSwitchBase-input-533' and @name = '6342' and @type = 'checkbox' and @aria-label = 'Select row'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;6342&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input-533</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6342</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-386 MuiBox-root-387&quot;]/div[@class=&quot;MuiBox-root-386 MuiBox-root-388&quot;]/div[@class=&quot;MuiBox-root-386 MuiBox-root-505&quot;]/div[@class=&quot;MuiTableContainer-root-506&quot;]/table[@class=&quot;MuiTable-root-507 makeStyles-table-374&quot;]/tbody[@class=&quot;MuiTableBody-root-534&quot;]/tr[@class=&quot;MuiTableRow-root-510&quot;]/td[@class=&quot;MuiTableCell-root-514 MuiTableCell-body-516 MuiTableCell-paddingCheckbox-519 MuiTableCell-sizeSmall-518&quot;]/span[@class=&quot;MuiButtonBase-root-476 MuiIconButton-root-468 PrivateSwitchBase-root-530 MuiCheckbox-root-526 MuiCheckbox-colorPrimary-528 MuiIconButton-colorPrimary-472&quot;]/span[@class=&quot;MuiIconButton-label-475&quot;]/input[@class=&quot;PrivateSwitchBase-input-533&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='6342']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div[4]/div/table/tbody/tr[3]/td/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
