<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min Inlcluded_max</name>
   <tag></tag>
   <elementGuidId>3e311e73-e9f3-4266-8861-5adae3ee1539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='max']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;max&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-664 MuiOutlinedInput-input-914 MuiInputBase-inputMarginDense-665 MuiOutlinedInput-inputMarginDense-915</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-731&quot;]/div[@class=&quot;MuiDialog-container-734 MuiDialog-scrollPaper-732&quot;]/div[@class=&quot;MuiPaper-root-840 MuiDialog-paper-735 MuiDialog-paperScrollPaper-736 MuiDialog-paperWidthSm-740 MuiPaper-elevation24-867 MuiPaper-rounded-841&quot;]/div[@class=&quot;MuiDialogContent-root-899&quot;]/div[@class=&quot;sc-cBoqAE cLLDPE&quot;]/div[@class=&quot;MuiFormControl-root-903 MuiTextField-root-902 MuiFormControl-marginDense-905&quot;]/div[@class=&quot;MuiInputBase-root-656 MuiOutlinedInput-root-907 Mui-focused Mui-focused MuiInputBase-formControl-657 MuiInputBase-marginDense-660 MuiOutlinedInput-marginDense-911&quot;]/input[@class=&quot;MuiInputBase-input-664 MuiOutlinedInput-input-914 MuiInputBase-inputMarginDense-665 MuiOutlinedInput-inputMarginDense-915&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='max']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
