<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>d716be81-4157-4058-b97c-ae8e8c83715e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Select feature by street name:'])[1]/following::div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-523.MuiOutlinedInput-root-571.MuiAutocomplete-inputRoot-549.MuiInputBase-fullWidth-530.MuiInputBase-formControl-524.MuiInputBase-adornedEnd-526.MuiOutlinedInput-adornedEnd-574.MuiInputBase-marginDense-527.MuiOutlinedInput-marginDense-575</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-root-523 MuiOutlinedInput-root-571 MuiAutocomplete-inputRoot-549 MuiInputBase-fullWidth-530 MuiInputBase-formControl-524 MuiInputBase-adornedEnd-526 MuiOutlinedInput-adornedEnd-574 MuiInputBase-marginDense-527 MuiOutlinedInput-marginDense-575</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-378 MuiBox-root-379 makeStyles-subPanel-374 makeStyles-subPanel-377&quot;]/div[@class=&quot;MuiBox-root-378 MuiBox-root-382&quot;]/div[@class=&quot;MuiBox-root-378 MuiBox-root-383&quot;]/div[@class=&quot;sc-hiKfDv fcCmgx&quot;]/div[@class=&quot;MuiBox-root-378 MuiBox-root-542&quot;]/div[@class=&quot;MuiAutocomplete-root-543 MuiAutocomplete-fullWidth-544 MuiAutocomplete-hasClearIcon-548 MuiAutocomplete-hasPopupIcon-547&quot;]/div[@class=&quot;MuiFormControl-root-567 MuiTextField-root-566 MuiFormControl-marginDense-569 MuiFormControl-fullWidth-570&quot;]/div[@class=&quot;MuiInputBase-root-523 MuiOutlinedInput-root-571 MuiAutocomplete-inputRoot-549 MuiInputBase-fullWidth-530 MuiInputBase-formControl-524 MuiInputBase-adornedEnd-526 MuiOutlinedInput-adornedEnd-574 MuiInputBase-marginDense-527 MuiOutlinedInput-marginDense-575&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select feature by street name:'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pavement Maintenance'])[2]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select feature on map to edit attribute values.'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
