<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_PCI_MuiTableCell-root-2349 MuiTableCell-_ca2ebd</name>
   <tag></tag>
   <elementGuidId>60018c3d-a8b0-43ad-8e63-81b064405d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[3]/div[2]/div/div/div[4]/div/table/tbody/tr[3]/td[2]/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root-2349 MuiTableCell-body-2351 makeStyles-tableCell-2214 null MuiTableCell-alignLeft-2356 MuiTableCell-sizeSmall-2353</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-25256</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-2221 MuiBox-root-2222&quot;]/div[@class=&quot;MuiBox-root-2221 MuiBox-root-2223&quot;]/div[@class=&quot;MuiBox-root-2221 MuiBox-root-2340&quot;]/div[@class=&quot;MuiTableContainer-root-2341&quot;]/table[@class=&quot;MuiTable-root-2342 makeStyles-table-2209&quot;]/tbody[@class=&quot;MuiTableBody-root-2369&quot;]/tr[@class=&quot;MuiTableRow-root-2345&quot;]/td[@class=&quot;MuiTableCell-root-2349 MuiTableCell-body-2351 MuiTableCell-alignCenter-2357 MuiTableCell-sizeSmall-2353&quot;]/tr[@class=&quot;MuiTableRow-root-2345&quot;]/td[@class=&quot;MuiTableCell-root-2349 MuiTableCell-body-2351 makeStyles-tableCell-2214 null MuiTableCell-alignLeft-2356 MuiTableCell-sizeSmall-2353&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div[2]/div/div/div[4]/div/table/tbody/tr[3]/td[2]/tr/td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCI'])[2]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stafford,Jon'])[1]/following::td[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shrutika Sawant'])[1]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restore'])[1]/preceding::td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/tr/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
