<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vaadin-grid-cell-content_Editor Id</name>
   <tag></tag>
   <elementGuidId>61a051be-0f85-455a-9bd6-d3587b99bae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[2]/div[3]/div/div[2]/div[14]/div/div[2]/div/div/vaadin-grid/vaadin-grid-cell-content[177]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-grid-cell-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>vaadin-grid-cell-content-176</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;17acb75181f-widget-167_grid&quot;)/vaadin-grid-cell-content[177]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//vaadin-grid[@id='17acb75181f-widget-167_grid']/vaadin-grid-cell-content[177]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/vaadin-grid/vaadin-grid-cell-content[177]</value>
   </webElementXpaths>
</WebElementEntity>
