version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/Dashboard_Layers' -apiKey="611c2ff0-6575-40e3-8fec-66df37a8f66a"