version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: 'cd "C:/Users/shrut/Desktop/Katalon/Katalon_Studio_Engine_Windows" && katalonc -noSplash -runMode=console -retry=0 -testSuitePath="Test Suites/Demo" -browserType="Chrome" -apiKey="05488a6b-57d1-40a0-a4b9-8ecdedc5680d"'
