version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: 'cd "C:/Users/shrut/Desktop/Katalon/Katalon_Studio_Engine_Windows" && katalonc -noSplash -runMode=console -projectPath="C:\Users\shrut\Katalon Studio\Streetlogix-GIS3.1-Tests\Streetlogix-GIS-Tests-Portland.prj" -retry=0 -testSuitePath="Test Suites/Demo" -executionProfile="default" -browserType="Chrome" -apiKey="05488a6b-57d1-40a0-a4b9-8ecdedc5680d" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'
