version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: 'cd "C:/Users/shrut/Desktop/Katalon/Katalon_Studio_Engine_Windows" && katalonc -noSplash -runMode=console -projectPath="%WORKSPACE%/Streetlogix-GIS-Tests-Portland.prj" -retry=0 -testSuitePath="Test Suites/Dashboard_Layers" -executionProfile="default" -browserType="Chrome" -apiKey="42c2bc68-24f4-46e7-b59e-5658c614dbfd" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'
