<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Assignee Name</name>
   <tag></tag>
   <elementGuidId>63fd9357-1822-4f29-afcf-c9851fedff55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.MuiTableCell-root-784.MuiTableCell-head-785.makeStyles-headCell-774.MuiTableCell-alignCenter-792.MuiTableCell-sizeSmall-788</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollable-auto-tabpanel-4']/div/div/table/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root-784 MuiTableCell-head-785 makeStyles-headCell-774 MuiTableCell-alignCenter-792 MuiTableCell-sizeSmall-788</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assignee Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollable-auto-tabpanel-4&quot;)/div[@class=&quot;MuiBox-root-384 MuiBox-root-772&quot;]/div[@class=&quot;MuiPaper-root-392 MuiTableContainer-root-776 MuiPaper-elevation1-396 MuiPaper-rounded-393&quot;]/table[@class=&quot;MuiTable-root-777 makeStyles-table-773&quot;]/thead[@class=&quot;MuiTableHead-root-779&quot;]/tr[@class=&quot;MuiTableRow-root-780 MuiTableRow-head-782&quot;]/th[@class=&quot;MuiTableCell-root-784 MuiTableCell-head-785 makeStyles-headCell-774 MuiTableCell-alignCenter-792 MuiTableCell-sizeSmall-788&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollable-auto-tabpanel-4']/div/div/table/thead/tr/th</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart'])[1]/following::th[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignee Name'])[1]/following::th[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultant_Admin Demo'])[1]/preceding::th[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
   </webElementXpaths>
</WebElementEntity>
