<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Others_1</name>
   <tag></tag>
   <elementGuidId>c0542f0c-f7fe-4baa-a0ac-53b224f03f9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[2]/div[1]/div/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div/div/div/div/div/div[2]/div[8]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
