<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scenario Name_MuiInputBase-input-440 _00d119_1_2_3</name>
   <tag></tag>
   <elementGuidId>d346cf1e-6157-4bc2-8c03-73174200cc97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-432.MuiInput-root-421.MuiInput-underline-424.Mui-focused.Mui-focused > input.MuiInputBase-input-440.MuiInput-input-428</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ATe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-440 MuiInput-input-428</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-390 makeStyles-subPanel-385 makeStyles-subPanel-388&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-393&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-394&quot;]/div[@class=&quot;sc-jcwpoC xgIFN&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-470&quot;]/div[@class=&quot;MuiInputBase-root-432 MuiInput-root-421 MuiInput-underline-424 Mui-focused Mui-focused&quot;]/input[@class=&quot;MuiInputBase-input-440 MuiInput-input-428&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div/div[4]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
