<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_11</name>
   <tag></tag>
   <elementGuidId>3eea25d3-e9b2-48fd-870f-b7fbd62de8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-432.MuiInput-root-421.MuiInput-underline-424.MuiInputBase-formControl-433.MuiInput-formControl-422 > input.MuiInputBase-input-440.MuiInput-input-428</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[99]/div[3]/div/div[2]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-440 MuiInput-input-428</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-474&quot;]/div[@class=&quot;MuiDialog-container-477 MuiDialog-scrollPaper-475&quot;]/div[@class=&quot;MuiPaper-root-579 MuiDialog-paper-478 MuiDialog-paperScrollPaper-479 MuiDialog-paperWidthSm-483 MuiPaper-elevation24-606 MuiPaper-rounded-580&quot;]/div[@class=&quot;MuiDialogContent-root-657&quot;]/div[@class=&quot;MuiFormControl-root-660 MuiTextField-root-659 makeStyles-formControl-472&quot;]/div[@class=&quot;MuiInputBase-root-432 MuiInput-root-421 MuiInput-underline-424 MuiInputBase-formControl-433 MuiInput-formControl-422&quot;]/input[@class=&quot;MuiInputBase-input-440 MuiInput-input-428&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
