<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_OtherAssests</name>
   <tag></tag>
   <elementGuidId>7436e3af-564b-4101-a768-0f4cc4e0cf5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/ul/li[8]/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
