<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Decrease opacity_esri-layer-list__chil_0d6485</name>
   <tag></tag>
   <elementGuidId>5b03a0fa-fd34-40f0-ae3f-522d3a548045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/ul/li[7]/div[1]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.esri-layer-list__item.esri-layer-list__item--has-children.esri-layer-list__item--updating > div.esri-layer-list__item-container > span.esri-layer-list__child-toggle > span.esri-layer-list__child-toggle-icon--closed.esri-icon-right-triangle-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>esri-layer-list__child-toggle-icon--closed esri-icon-right-triangle-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-20 MuiBox-root-21&quot;]/div[@class=&quot;MuiBox-root-20 MuiBox-root-22&quot;]/div[@class=&quot;makeStyles-multiWidgetPanel-16&quot;]/div[@class=&quot;makeStyles-subWidgetPanel-17&quot;]/div[@class=&quot;esri-layer-list esri-widget esri-widget--panel&quot;]/ul[@class=&quot;esri-layer-list__list esri-layer-list__list--root esri-layer-list__list--independent&quot;]/li[@class=&quot;esri-layer-list__item esri-layer-list__item--has-children esri-layer-list__item--updating&quot;]/div[@class=&quot;esri-layer-list__item-container&quot;]/span[@class=&quot;esri-layer-list__child-toggle&quot;]/span[@class=&quot;esri-layer-list__child-toggle-icon--closed esri-icon-right-triangle-arrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div/div[2]/div/ul/li[7]/div/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/span/span</value>
   </webElementXpaths>
</WebElementEntity>
