<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>75cb785d-8dfb-426a-a060-1c8eec514691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-4013.MuiOutlinedInput-root-4070.MuiAutocomplete-inputRoot-4048.MuiInputBase-fullWidth-4020.Mui-focused.Mui-focused.MuiInputBase-formControl-4014.MuiInputBase-adornedEnd-4016.MuiOutlinedInput-adornedEnd-4073.MuiInputBase-marginDense-4017.MuiOutlinedInput-marginDense-4074</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[15]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-root-4013 MuiOutlinedInput-root-4070 MuiAutocomplete-inputRoot-4048 MuiInputBase-fullWidth-4020 Mui-focused Mui-focused MuiInputBase-formControl-4014 MuiInputBase-adornedEnd-4016 MuiOutlinedInput-adornedEnd-4073 MuiInputBase-marginDense-4017 MuiOutlinedInput-marginDense-4074</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-3970 MuiBox-root-4137 makeStyles-subPanel-3966 makeStyles-subPanel-4136&quot;]/div[@class=&quot;MuiBox-root-3970 MuiBox-root-4140&quot;]/div[@class=&quot;MuiBox-root-3970 MuiBox-root-4141&quot;]/div[@class=&quot;sc-iTVJFM iTijYB&quot;]/div[@class=&quot;MuiAutocomplete-root-4042 Mui-focused MuiAutocomplete-hasClearIcon-4047&quot;]/div[@class=&quot;MuiFormControl-root-4066 MuiTextField-root-4065 MuiFormControl-marginDense-4068 MuiFormControl-fullWidth-4069&quot;]/div[@class=&quot;MuiInputBase-root-4013 MuiOutlinedInput-root-4070 MuiAutocomplete-inputRoot-4048 MuiInputBase-fullWidth-4020 Mui-focused Mui-focused MuiInputBase-formControl-4014 MuiInputBase-adornedEnd-4016 MuiOutlinedInput-adornedEnd-4073 MuiInputBase-marginDense-4017 MuiOutlinedInput-marginDense-4074&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[15]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[15]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[14]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[17]/preceding::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
