<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Repair Method</name>
   <tag></tag>
   <elementGuidId>044aa4d5-93d0-48a4-96e6-ed733ee7945b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;last_repair_method&quot;] > div.MuiFormControl-root-574.MuiTextField-root-573.MuiFormControl-marginDense-576.MuiFormControl-fullWidth-577 > div.MuiInputBase-root-530.MuiOutlinedInput-root-578.MuiAutocomplete-inputRoot-556.MuiInputBase-fullWidth-537.MuiInputBase-formControl-531.MuiInputBase-adornedEnd-533.MuiOutlinedInput-adornedEnd-581.MuiInputBase-marginDense-534.MuiOutlinedInput-marginDense-582 > #free-solo-with-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='free-solo-with-text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>free-solo-with-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-538 MuiOutlinedInput-input-585 MuiAutocomplete-input-557 MuiAutocomplete-inputFocused-558 MuiInputBase-inputAdornedEnd-543 MuiOutlinedInput-inputAdornedEnd-589 MuiInputBase-inputMarginDense-539 MuiOutlinedInput-inputMarginDense-586</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-385 MuiBox-root-392 makeStyles-subPanel-381 makeStyles-subPanel-391&quot;]/div[@class=&quot;MuiBox-root-385 MuiBox-root-395&quot;]/div[@class=&quot;MuiBox-root-385 MuiBox-root-396&quot;]/div[@class=&quot;sc-iTVJFM iTijYB&quot;]/div[@class=&quot;MuiAutocomplete-root-550 MuiAutocomplete-hasClearIcon-555&quot;]/div[@class=&quot;MuiFormControl-root-574 MuiTextField-root-573 MuiFormControl-marginDense-576 MuiFormControl-fullWidth-577&quot;]/div[@class=&quot;MuiInputBase-root-530 MuiOutlinedInput-root-578 MuiAutocomplete-inputRoot-556 MuiInputBase-fullWidth-537 MuiInputBase-formControl-531 MuiInputBase-adornedEnd-533 MuiOutlinedInput-adornedEnd-581 MuiInputBase-marginDense-534 MuiOutlinedInput-marginDense-582&quot;]/input[@id=&quot;free-solo-with-text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='free-solo-with-text'])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[15]/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
