<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Demo Admin_6368</name>
   <tag></tag>
   <elementGuidId>0bbf1428-4cf0-42cc-9fc6-d403e3a91abd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'PrivateSwitchBase-input-2642']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[3]/div[2]/div/div[1]/div[4]/div/table/thead/tr[1]/th[1]/span/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;6368&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input-2642</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6368</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-2495 MuiBox-root-2496&quot;]/div[@class=&quot;MuiBox-root-2495 MuiBox-root-2497&quot;]/div[@class=&quot;MuiBox-root-2495 MuiBox-root-2614&quot;]/div[@class=&quot;MuiTableContainer-root-2615&quot;]/table[@class=&quot;MuiTable-root-2616 makeStyles-table-2483&quot;]/tbody[@class=&quot;MuiTableBody-root-2643&quot;]/tr[@class=&quot;MuiTableRow-root-2619&quot;]/td[@class=&quot;MuiTableCell-root-2623 MuiTableCell-body-2625 MuiTableCell-paddingCheckbox-2628 MuiTableCell-sizeSmall-2627&quot;]/span[@class=&quot;MuiButtonBase-root-2585 MuiIconButton-root-2577 PrivateSwitchBase-root-2639 MuiCheckbox-root-2635 MuiCheckbox-colorPrimary-2637 MuiIconButton-colorPrimary-2581&quot;]/span[@class=&quot;MuiIconButton-label-2584&quot;]/input[@class=&quot;PrivateSwitchBase-input-2642&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='6368']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div[2]/div/div/div[4]/div/table/tbody/tr[14]/td/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
