<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Demo Admin_6361</name>
   <tag></tag>
   <elementGuidId>c60f579b-a708-4507-afb8-a6264552a499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;6361&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='6361']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input-1975</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6361</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-1828 MuiBox-root-1829&quot;]/div[@class=&quot;MuiBox-root-1828 MuiBox-root-1830&quot;]/div[@class=&quot;MuiBox-root-1828 MuiBox-root-1947&quot;]/div[@class=&quot;MuiTableContainer-root-1948&quot;]/table[@class=&quot;MuiTable-root-1949 makeStyles-table-1816&quot;]/tbody[@class=&quot;MuiTableBody-root-1976&quot;]/tr[@class=&quot;MuiTableRow-root-1952&quot;]/td[@class=&quot;MuiTableCell-root-1956 MuiTableCell-body-1958 MuiTableCell-paddingCheckbox-1961 MuiTableCell-sizeSmall-1960&quot;]/span[@class=&quot;MuiButtonBase-root-1918 MuiIconButton-root-1910 PrivateSwitchBase-root-1972 MuiCheckbox-root-1968 MuiCheckbox-colorPrimary-1970 MuiIconButton-colorPrimary-1914&quot;]/span[@class=&quot;MuiIconButton-label-1917&quot;]/input[@class=&quot;PrivateSwitchBase-input-1975&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='6361']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div[2]/div/div/div[4]/div/table/tbody/tr[13]/td/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
