<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__surface_type_id</name>
   <tag></tag>
   <elementGuidId>1534c0b7-64c4-494e-b319-180ad1716c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;surface_type_id&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='surface_type_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>surface_type_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-538 MuiOutlinedInput-input-585 MuiInputBase-inputMarginDense-539 MuiOutlinedInput-inputMarginDense-586</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-385 MuiBox-root-392 makeStyles-subPanel-381 makeStyles-subPanel-391&quot;]/div[@class=&quot;MuiBox-root-385 MuiBox-root-395&quot;]/div[@class=&quot;MuiBox-root-385 MuiBox-root-396&quot;]/div[@class=&quot;sc-iTVJFM iTijYB&quot;]/div[@class=&quot;MuiFormControl-root-574 MuiTextField-root-573 MuiFormControl-marginDense-576&quot;]/div[@class=&quot;MuiInputBase-root-530 MuiOutlinedInput-root-578 Mui-focused Mui-focused MuiInputBase-formControl-531 MuiInputBase-marginDense-534 MuiOutlinedInput-marginDense-582&quot;]/input[@class=&quot;MuiInputBase-input-538 MuiOutlinedInput-input-585 MuiInputBase-inputMarginDense-539 MuiOutlinedInput-inputMarginDense-586&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='surface_type_id']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[31]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
