<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PM_layer</name>
   <tag></tag>
   <elementGuidId>9d456ce4-6103-4b9a-9f0f-bad3897b7cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/ul/li[1]/div[1]/div[1]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
