<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Zoom out_esri-icon esri-icon-home</name>
   <tag></tag>
   <elementGuidId>aeca247d-dec2-4d2f-9590-873ff1c6f2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/div/div/div/div[3]/div/div[4]/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.esri-icon.esri-icon-home</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>esri-icon esri-icon-home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[2]/div[1]/div[@class=&quot;webmap makeStyles-attributeTable-1 makeStyles-attributeTable-2 esri-view esri-view-width-small esri-view-width-greater-than-xsmall esri-view-width-less-than-medium esri-view-width-less-than-large esri-view-width-less-than-xlarge esri-view-height-xsmall esri-view-height-less-than-small esri-view-height-less-than-medium esri-view-height-less-than-large esri-view-height-less-than-xlarge esri-view-orientation-landscape&quot;]/div[@class=&quot;esri-view-root&quot;]/div[@class=&quot;esri-ui&quot;]/div[@class=&quot;esri-ui-inner-container esri-ui-corner-container&quot;]/div[@class=&quot;esri-ui-bottom-right esri-ui-corner&quot;]/div[@class=&quot;esri-component esri-home esri-widget--button esri-widget&quot;]/span[@class=&quot;esri-icon esri-icon-home&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div/div[3]/div/div[4]/div[2]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
