<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_22</name>
   <tag></tag>
   <elementGuidId>b687ebd7-c994-497e-866a-7e069cf5a302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[81]/div[3]/div/div[2]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-439 MuiInput-input-427</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-472&quot;]/div[@class=&quot;MuiDialog-container-475 MuiDialog-scrollPaper-473&quot;]/div[@class=&quot;MuiPaper-root-540 MuiDialog-paper-476 MuiDialog-paperScrollPaper-477 MuiDialog-paperWidthSm-481 MuiPaper-elevation24-567 MuiPaper-rounded-541&quot;]/div[@class=&quot;MuiDialogContent-root-649&quot;]/div[@class=&quot;MuiFormControl-root-652 MuiTextField-root-651 makeStyles-formControl-470&quot;]/div[@class=&quot;MuiInputBase-root-431 MuiInput-root-420 MuiInput-underline-423 MuiInputBase-formControl-432 MuiInput-formControl-421&quot;]/input[@class=&quot;MuiInputBase-input-439 MuiInput-input-427&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
