<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload_asphalt(tons)</name>
   <tag></tag>
   <elementGuidId>6653b033-7038-442b-a236-7622a207d038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='asphalt(tons)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;asphalt(tons)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asphalt(tons)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-1295 MuiOutlinedInput-input-1327 MuiInputBase-inputMarginDense-1296 MuiOutlinedInput-inputMarginDense-1328</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYwzuL hKaSEl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-1230 MuiBox-root-1385 makeStyles-subPanel-1226 makeStyles-subPanel-1384&quot;]/div[@class=&quot;MuiBox-root-1230 MuiBox-root-1390&quot;]/div[@class=&quot;MuiBox-root-1230 MuiBox-root-1391&quot;]/div[@class=&quot;sc-hiKfDv jxKoMp&quot;]/div[@class=&quot;MuiFormControl-root-1316 MuiTextField-root-1315 MuiFormControl-marginDense-1318&quot;]/div[@class=&quot;MuiInputBase-root-1287 MuiOutlinedInput-root-1320 Mui-focused Mui-focused MuiInputBase-formControl-1288 MuiInputBase-marginDense-1291 MuiOutlinedInput-marginDense-1324&quot;]/input[@class=&quot;MuiInputBase-input-1295 MuiOutlinedInput-input-1327 MuiInputBase-inputMarginDense-1296 MuiOutlinedInput-inputMarginDense-1328&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='asphalt(tons)']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[11]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
