<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Labor_Quantity2</name>
   <tag></tag>
   <elementGuidId>a349944a-e908-455e-818d-633176acfbaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[18]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Qty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-858 MuiOutlinedInput-input-890 Mui-disabled Mui-disabled jss1038 jss1172 MuiInputBase-inputMarginDense-859 MuiOutlinedInput-inputMarginDense-891</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cBoqAE lRfdj&quot;]/div[@class=&quot;sc-dIsUp jEEywD&quot;]/div[@class=&quot;sc-iCoGMd dLtoTP visible&quot;]/div[@class=&quot;sc-pNWdM XJxhY&quot;]/div[@class=&quot;MuiBox-root-793 jss948 jss789 jss947&quot;]/div[@class=&quot;MuiBox-root-793 jss953&quot;]/div[@class=&quot;MuiBox-root-793 jss954&quot;]/div[@class=&quot;value&quot;]/div[@class=&quot;sc-iJCRrE lboiNp&quot;]/div[@class=&quot;MuiFormControl-root-879 MuiTextField-root-878 MuiFormControl-marginDense-881&quot;]/div[@class=&quot;MuiInputBase-root-850 MuiOutlinedInput-root-883 jss1037 Mui-disabled Mui-disabled jss1038 jss1172 MuiInputBase-formControl-851 MuiInputBase-marginDense-854 MuiOutlinedInput-marginDense-887 jss1039&quot;]/input[@class=&quot;MuiInputBase-input-858 MuiOutlinedInput-input-890 Mui-disabled Mui-disabled jss1038 jss1172 MuiInputBase-inputMarginDense-859 MuiOutlinedInput-inputMarginDense-891&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[18]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[13]/div[3]/div[3]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[3]/div[3]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
