<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All Groups_MuiInputBase-input-450 Mui_1e97bd</name>
   <tag></tag>
   <elementGuidId>d3f0454b-a1b1-4547-b809-7fc1794c6d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.MuiInputBase-input-450.MuiOutlinedInput-input-437.MuiInputBase-inputMarginDense-451.MuiOutlinedInput-inputMarginDense-438</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-450 MuiOutlinedInput-input-437 MuiInputBase-inputMarginDense-451 MuiOutlinedInput-inputMarginDense-438</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cBoqAE gLDehl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd cbDJXF visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-390 makeStyles-subPanel-385 makeStyles-subPanel-388&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-393&quot;]/div[@class=&quot;MuiBox-root-389 MuiBox-root-394&quot;]/div[@class=&quot;sc-lmgQwP cnHywr&quot;]/div[@class=&quot;MuiFormControl-root-426 MuiTextField-root-425 MuiFormControl-marginDense-428&quot;]/div[@class=&quot;MuiInputBase-root-442 MuiOutlinedInput-root-430 Mui-focused Mui-focused MuiInputBase-formControl-443 MuiInputBase-marginDense-446 MuiOutlinedInput-marginDense-434&quot;]/input[@class=&quot;MuiInputBase-input-450 MuiOutlinedInput-input-437 MuiInputBase-inputMarginDense-451 MuiOutlinedInput-inputMarginDense-438&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
