<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Euipment_Switch</name>
   <tag></tag>
   <elementGuidId>67cb23b7-1ca2-48e1-adc1-019a2b228a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/div/div[1]/div[13]/div/span/span[1]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.value > div.sc-lmgQwP.hpRDUw > span.MuiSwitch-root-961 > span.MuiButtonBase-root-911.MuiIconButton-root-939.jss971.MuiSwitch-switchBase-964.MuiSwitch-colorPrimary-965 > span.MuiIconButton-label-946 > input.jss974.MuiSwitch-input-968</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Equipment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss974 MuiSwitch-input-968</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cBoqAE lRfdj&quot;]/div[@class=&quot;sc-dIsUp jEEywD&quot;]/div[@class=&quot;sc-iCoGMd dLtoTP visible&quot;]/div[@class=&quot;sc-pNWdM XJxhY&quot;]/div[@class=&quot;MuiBox-root-793 jss948 jss789 jss947&quot;]/div[@class=&quot;MuiBox-root-793 jss953&quot;]/div[@class=&quot;MuiBox-root-793 jss954&quot;]/div[@class=&quot;value&quot;]/div[@class=&quot;sc-lmgQwP hpRDUw&quot;]/span[@class=&quot;MuiSwitch-root-961&quot;]/span[@class=&quot;MuiButtonBase-root-911 MuiIconButton-root-939 jss971 MuiSwitch-switchBase-964 MuiSwitch-colorPrimary-965&quot;]/span[@class=&quot;MuiIconButton-label-946&quot;]/input[@class=&quot;jss974 MuiSwitch-input-968&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Equipment</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[11]/div/span/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/span/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
