<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__MuiInputBase-input-858 MuiOutlinedIn_29912f</name>
   <tag></tag>
   <elementGuidId>fac22c5c-b1d7-41fb-98b0-6b8baf0d7d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-850.MuiOutlinedInput-root-883.makeStyles-root-1081.Mui-focused.Mui-focused.MuiInputBase-formControl-851.MuiInputBase-marginDense-854.MuiOutlinedInput-marginDense-887.makeStyles-marginDense-1083 > input.MuiInputBase-input-858.MuiOutlinedInput-input-890.MuiInputBase-inputMarginDense-859.MuiOutlinedInput-inputMarginDense-891</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Qty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-858 MuiOutlinedInput-input-890 MuiInputBase-inputMarginDense-859 MuiOutlinedInput-inputMarginDense-891</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cBoqAE gLDehl&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd cbDJXF visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-793 MuiBox-root-948 makeStyles-subPanel-789 makeStyles-subPanel-947&quot;]/div[@class=&quot;MuiBox-root-793 MuiBox-root-953&quot;]/div[@class=&quot;MuiBox-root-793 MuiBox-root-954&quot;]/div[@class=&quot;value&quot;]/div[@class=&quot;sc-iJCRrE jSceTJ&quot;]/div[@class=&quot;MuiFormControl-root-879 MuiTextField-root-878 MuiFormControl-marginDense-881&quot;]/div[@class=&quot;MuiInputBase-root-850 MuiOutlinedInput-root-883 makeStyles-root-1081 Mui-focused Mui-focused MuiInputBase-formControl-851 MuiInputBase-marginDense-854 MuiOutlinedInput-marginDense-887 makeStyles-marginDense-1083&quot;]/input[@class=&quot;MuiInputBase-input-858 MuiOutlinedInput-input-890 MuiInputBase-inputMarginDense-859 MuiOutlinedInput-inputMarginDense-891&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div[11]/div[2]/div[3]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
