<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>b0ae7306-e41d-4971-8eb9-3f41f34f7f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.MuiTableCell-root-689.MuiTableCell-body-691.MuiTableCell-alignCenter-697</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root-689 MuiTableCell-body-691 MuiTableCell-alignCenter-697</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hiKfDv tAuRw&quot;]/div[@class=&quot;sc-dIsUp eioKjI&quot;]/div[@class=&quot;sc-iCoGMd bfMiYE visible&quot;]/div[@class=&quot;sc-pNWdM kieaXL&quot;]/div[@class=&quot;MuiBox-root-388 MuiBox-root-597 makeStyles-subPanel-384 makeStyles-subPanel-596&quot;]/div[@class=&quot;MuiBox-root-388 MuiBox-root-600&quot;]/div[@class=&quot;MuiBox-root-388 MuiBox-root-601&quot;]/div[@class=&quot;MuiPaper-root-540 makeStyles-resultCard-383 MuiPaper-elevation1-544 MuiPaper-rounded-541&quot;]/div[@class=&quot;MuiBox-root-388 MuiBox-root-678&quot;]/div[@class=&quot;MuiPaper-root-540 MuiTableContainer-root-681 MuiPaper-elevation1-544 MuiPaper-rounded-541&quot;]/table[@class=&quot;MuiTable-root-682&quot;]/tbody[@class=&quot;MuiTableBody-root-701&quot;]/tr[@class=&quot;MuiTableRow-root-685 makeStyles-bodyRow-680&quot;]/td[@class=&quot;MuiTableCell-root-689 MuiTableCell-body-691 MuiTableCell-alignCenter-697&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/table/tbody/tr/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condition Index'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Budget'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
   </webElementXpaths>
</WebElementEntity>
