<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PCI_min2</name>
   <tag></tag>
   <elementGuidId>0d8f5182-2d2c-425f-9e34-5db1238db8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='min']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;min&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-527 MuiOutlinedInput-input-1086 MuiInputBase-inputMarginDense-528 MuiOutlinedInput-inputMarginDense-1087</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-454&quot;]/div[@class=&quot;MuiDialog-container-457 MuiDialog-scrollPaper-455&quot;]/div[@class=&quot;MuiPaper-root-1012 MuiDialog-paper-458 MuiDialog-paperScrollPaper-459 MuiDialog-paperWidthSm-463 MuiPaper-elevation24-1039 MuiPaper-rounded-1013&quot;]/div[@class=&quot;MuiDialogContent-root-1071&quot;]/div[@class=&quot;sc-iBzEeX jeJnia&quot;]/div[@class=&quot;MuiFormControl-root-1075 MuiTextField-root-1074 MuiFormControl-marginDense-1077&quot;]/div[@class=&quot;MuiInputBase-root-519 MuiOutlinedInput-root-1079 MuiInputBase-formControl-520 MuiInputBase-marginDense-523 MuiOutlinedInput-marginDense-1083&quot;]/input[@class=&quot;MuiInputBase-input-527 MuiOutlinedInput-input-1086 MuiInputBase-inputMarginDense-528 MuiOutlinedInput-inputMarginDense-1087&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='min']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[177]/div[3]/div/div[2]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
