<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Node_ms1</name>
   <tag></tag>
   <elementGuidId>a95a4ce3-14be-479b-a8e4-3a9ed57c056e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ms&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ms</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-527 MuiOutlinedInput-input-1203 MuiInputBase-inputMarginDense-528 MuiOutlinedInput-inputMarginDense-1204</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-454&quot;]/div[@class=&quot;MuiDialog-container-457 MuiDialog-scrollPaper-455&quot;]/div[@class=&quot;MuiPaper-root-1130 MuiDialog-paper-458 MuiDialog-paperScrollPaper-459 MuiDialog-paperWidthSm-463 MuiPaper-elevation24-1157 MuiPaper-rounded-1131&quot;]/div[@class=&quot;MuiDialogContent-root-1189&quot;]/div[@class=&quot;sc-iBzEeX jeJnia&quot;]/div[@class=&quot;MuiFormControl-root-1192 MuiTextField-root-1191 MuiFormControl-marginDense-1194&quot;]/div[@class=&quot;MuiInputBase-root-519 MuiOutlinedInput-root-1196 Mui-focused Mui-focused MuiInputBase-formControl-520 MuiInputBase-marginDense-523 MuiOutlinedInput-marginDense-1200&quot;]/input[@class=&quot;MuiInputBase-input-527 MuiOutlinedInput-input-1203 MuiInputBase-inputMarginDense-528 MuiOutlinedInput-inputMarginDense-1204&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ms']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[177]/div[3]/div/div[2]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
