<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Decision Tree Name_dtName</name>
   <tag></tag>
   <elementGuidId>59919350-0c34-4c65-97fa-7c88df399c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dtName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dtName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dtName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-527 MuiOutlinedInput-input-2045 MuiInputBase-inputMarginDense-528 MuiOutlinedInput-inputMarginDense-2046</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-454&quot;]/div[@class=&quot;MuiDialog-container-457 MuiDialog-scrollPaper-455&quot;]/div[@class=&quot;MuiPaper-root-1971 MuiDialog-paper-458 MuiDialog-paperScrollPaper-459 MuiDialog-paperWidthSm-463 MuiPaper-elevation24-1998 MuiPaper-rounded-1972&quot;]/div[@class=&quot;MuiDialogContent-root-2030&quot;]/div[@class=&quot;MuiFormControl-root-2034 MuiTextField-root-2033 MuiFormControl-marginDense-2036&quot;]/div[@class=&quot;MuiInputBase-root-519 MuiOutlinedInput-root-2038 Mui-focused Mui-focused MuiInputBase-formControl-520 MuiInputBase-marginDense-523 MuiOutlinedInput-marginDense-2042&quot;]/input[@class=&quot;MuiInputBase-input-527 MuiOutlinedInput-input-2045 MuiInputBase-inputMarginDense-528 MuiOutlinedInput-inputMarginDense-2046&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dtName']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
